services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cactoo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"   # Interface web MailDev
      - "1025:1025"   # Port SMTP
    restart: unless-stopped

volumes:
  postgres_data: