services:
  postgres:
    image: postgres:15
    container_name: archi-logicielle
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cactoo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
